### PR TITLE
AMP Review 1

### PR DESCRIPTION
**Pull request by cjwallace**
The overall content of the notebook is excellent, but I encountered a few technical issues while performing AMP Review 1. Testing on CDP Public (while nightly is down). It's possible some result from the bundled libraries in CDP.

- [x] No master branch, so created one. I prefer "main" but CML requires "master" or the project imports empty.
- [x] Add a "how to deploy on CML" section to README.
- [x] `pip` should be `pip3` in first code cell of notebook because CML defaults to python 2.7.
- [x] The engine comes with a bunch of libs pre-installed, and one conflicts with a sklearn requirement. Need to add `!pip3 uninstall -qy joblib` to the top of the first code cell, then reinstall joblib in the second line. This error was not thrown on FFLab-4.
- [x] Missing xgboost dependency.
- [x] Hit `LinAlgError: singular matrix` error on the seaborn pairplot.
- [x] Hit `PicklingError: Can't pickle <class 'collections.FlatTree'>: it's not found as collections.FlatTree
tracing...` on  PCA plot. I wonder if this is a default library thing too.
- [x] Some 2-space indenting, which causes Jupyter syntax highlighting to misfire on some stuff. Made it all 4-space. In general I wonder if it's worth applying a formatter to notebook code (and if a linter for notebook code exists 🤔 ).
- [x] The final cell is causing a kernel restart on 2GB RAM, so include in README that 4GB RAM required.
- [x] On fflab-4 I get a bunch of TypeErrors for adding a str to a float in the chart axis labels. Don't get this on CDP Public, so I think it's a CDSW/CML matplotlib version thing (since they're on different engines), if I were to guess. Will diagnose further.

### CODE REVIEW

**Comment by cjwallace** [comment]
Will continue tomorrow, but @andrewrreed, fyi. We should think about (I think you and eng already have?) specifying engine version in the declaration file. A lot of the above issues are inconsistent between engines (I guess due to dependencies).

As a mitigation tactic, since changing, eg, matplotlib, only breaks things in the CML session view, maybe we should just always install all dependencies that get imported the first cell of a notebook. Though this wouldn't fix things like the joblib issue, where, despite a compatible version, the fix was a hard uninstall and reinstall. Ramble ramble ramble.

**Comment by andrewrreed** [comment]
> Will continue tomorrow, but @andrewrreed, fyi. We should think about (I think you and eng already have?) specifying engine version in the declaration file. A lot of the above issues are inconsistent between engines (I guess due to dependencies).
> 
> As a mitigation tactic, since changing, eg, matplotlib, only breaks things in the CML session view, maybe we should just always install all dependencies that get imported the first cell of a notebook. Though this wouldn't fix things like the joblib issue, where, despite a compatible version, the fix was a hard uninstall and reinstall. Ramble ramble ramble.

There is a long background story and plan for this moving forward, but the TLDR is that we will be designing a way to specify environment characteristics for runtimes, but not for engines since the will soon be deprecated. For now, I agree that installing [version pinned] dependencies upfront should be a good mitigation tactic and will have to deal with the `joblib` workaround manually for now.

As an FYI - I just checked FFlab-4 and it looks like the default engine is v10 which will likely cause some issues for us: 
image


Any reservations on bumping our default to the latest (v13)?

**Comment by cjwallace** [comment]
> Any reservations on bumping our default to the latest (v13)?

I'd hold off, since that particular v13 engine doesn't come with Jupyter (just tried). I actually can't find the v13 engine that's in CDP public in the internal docker repos. Might be a permissions thing.

**Comment by cjwallace** [comment]
I _think_ the axis label type errors are taken care of (by the right selection of library versions, I guess. Possibly I had something locally installed in a CDSW project that was the problem, but I've no idea what, these projects are short lived). The only remaining blocker to the first review is the pickling error. This comes from UMAP, and we're definitely not the first to find it. Working on it.

**Comment by cjwallace** [comment]
Ok. I believe all issues are fixed, but I'd appreciate a second opinion (@andrewrreed  or @victordibia - _**no worries**_ if you're too busy right now Victor) before this is merged. I also made a few non-essential changes, like putting all imports up top so that the notebook errors right away if a dependency is not met.

**Comment by andrewrreed** [comment]
@cjwallace From a glance all looks good. I'll merge this now, and take a more thorough look (and suggest any updates in a new PR) with Review 2. Thanks!

**Pull request merged**
